### ISSUE TITLE
Selecting "All In" option in stock market can select more than I can buy

### ISSUE THREAD

**Issue by micaminoff** [wol-soft/beerplop#89]
Hopefully the issue's title is clear. At 1e+25 plops, I attempted to buy Beer Glasses at 8k price using "All In". The amount that was filled into the "Amount" field seemingly exceeded the currently available amount and I got a prompt to select a value less than xxxx.

I would expect the "All In" button to select the max buyable amount, limited by both current plops and currently available amount.

**Comment by wol-soft** [comment]
Hi @micaminoff,

the All In button takes the current amount of Plops and calculates how many Beer Glasses (or Malt/Hop, whatever you selected to trade with) can be purchased with 90% of the current Plops. The result is filled into the "Amount" field. So there is a 10% buffer for changes of the current Beer Glass price (the current market price, updates each second) which should be enough to start the deal in my experience (I played around a little bit with it and was not able to reproduce the issue currently).

If you fill the amount field with the All In button and wait for a while the current price may change into a direction so the filled amount exceeds the currently available amount as you describe (then you can hit the All In button again to update the filled amount to match the 90% investment again).

Another problem which can lead to the described problem may be automation (I don't know if you have unlocked Auto Buyers or Auto Level Ups). In this case the automation may purchase things so the plops are removed and the filled amount is no longer available due to the reduced amount of available Plops. As the automation may purchase items on each tick it may become difficult to purchase holds at the Stock Market with the All In button.

A possible solution which comes to my mind is an option at the Stock Market to update the filled amount on each tick automatically to match the 90% purchase which yhould then lead to a filled amount which is always inside the currently available amount. What do you think?

**Comment by micaminoff** [comment]
Hey, I don't have any automation yet. I can't seem to reproduce it now either. I could have sworn I tried pressing the All In-button again and still not being able to buy the selected amount, but I may be misremembering. If I encounter this again I'll try to be more thorough with documentation and reporting. imo you can close this for now. Thanks for a great game and merry christmas 🎄

**Comment by wol-soft** [comment]
Alright. Thanks for the fast reply and feel free to open the issue again if the issue occurs again. I'll have a look into the behaviour when automation is unlocked to see if it causes the problems I currently imagine.
Happy to hear you enjoy the game. Merry christmas 😃
