### ISSUE TITLE
Game stops when tab not focused - Google Chrome

### ISSUE THREAD

**Issue by SquaredGrunt** [wol-soft/beerplop#96]
Hi,

I noticed that in Chrome 80.0.3987.132 (64 bits), game is stopped when its tab is not focused for a few minutes.
Is there any way to fix that ?

**Comment by wol-soft** [comment]
Hi @SquaredGrunt,

nice to hear you are still playing the game :)

As far as I know chrome checks the CPU time and the memory consumed by background tabs. If the values exceed a limit they are reduced which basically stops the game (as it has to execute quite a few calculations on each iteration, they may exceed the CPU time limit given by Chrome. Many factory involved I guess like the general power of the computer, other running processes etc.). That's at least my idea what could cause the problem as I've seen a similar behaviour in Firefox due to resource limitation. The resources for background tabs are limited to provide more resources for the focussed tab (so it can be handled faster).

A possible hack around this which works in Firefox (I personally didn't experience this behaviour in Chrome until now) is to open the game in a separate window which has no additional tabs opened. In Firefox this tab is then considered active (even if the window isn't in the foreground, but the window has to be opened, not minimized. If minimized the tab is considered as a background tab).

Hope this helps.

Cheers!

**Comment by SquaredGrunt** [comment]
OK. Something might have changed recently in Chrome, until last week or so I didn't have this issue with beerplop. Or I have too many opened tabs!
I will open the game in its window. It will only by my 4th game opened that way :rofl: 

Thanks for your thorough answer !
